---
title: "find guldet"
subtitle: "Hvis du kan få adgang..."
format: 
  revealjs:
    logo: "kubdatalab.png"
    drop:
      button: true
      shortcut: "å"
    webr:
      packages:
        - ggplot2
        - dplyr
        - plotDK
    revealjs-plugins:
      - drop
---

## Udfordring!

curl virker ikke nativt i webassembler.
Men der skulle eksistere en workaround beskrevet her:

https://jeroen.github.io/notes/webassembly-curl/

Men det hjælper os ikke... Så i stedet må vi kigge på en GET løsning - gennem - url 
https://api.statbank.dk/console#data

Hvilket  - med det parametre der angives senere, giver:
https://api.statbank.dk/v1/data/HFUDD11/CSV?BOPOMR=*&HFUDD=H10%2C%20H20%2C%20H30%2C%20H40%2C%20H50%2C%20H60%2C%20H70%2C%20H80%2C%20H90&Tid=2024


Men det fejler. Chatty hjælper til:
https://api.statbank.dk/v1/data/HFUDD11/CSV?BOPOMR=*&HFUDD=H10,H20&Tid=2024
så skal vi "bare" have tilføjet resten af H'erne.

Og det virker!
## Housekeeping

Gå til denne side i din browser
. . . 
Følg med ved at bruge piletasterne.
. . . 
Stil endelig spørgsmål!

## målet
Sådan da. Vi skal nok have den gennem ggplotly så vi faktisk kan styre farverne.
```{r echo = FALSE} 
library(httr2)
library(dplyr)
endpoint <- "http://api.statbank.dk/v1/data"

variables <- list(list(code = "BOPOMR", values = I("*")),
                  list(code = "HFUDD", values = c("H10", "H20", "H30", "H40", "H50", "H60", "H70", "H80", "H90")),
                  list(code = "Tid", values = I(2024))
              )

our_body <- list(table = "HFUDD11", lang = "da", format = "CSV", variables = variables)



resp <- request(endpoint) |>
  req_body_json(our_body) |>
  req_perform()

csv_text <- resp_body_string(resp)


df <- read.csv2(text = csv_text)
df <- df |>mutate(BOPOMR = tolower(BOPOMR))

library(plotDK)
library(dplyr)
library(ggplot2)

df |> 
  group_by(BOPOMR) |> 
  mutate(totbefolk = sum(INDHOLD)) |> 
  mutate(andel = INDHOLD/totbefolk) |> 
  filter(HFUDD == "H10 Grundskole") |> 
plotDK::plotDK(id = "BOPOMR", value = "andel", interactive = TRUE) 
```




## KUB Datalab

Hvem er vi?

## Hvad vil vi vise?

Vi vil hente noget data fra Danmarks Statistik.

og så vil vi gøre ting med det

Vi bruger denne tabel fra DS

HFUDD11


## Hvordan gør jeg det derhjemme?

Hvis du vil lave noget der er mere avanceret end det her - så download og installer R og Positron fra
disse adresser


## Det samlede script

Her sætter vi det samlede færdige script ind, lige til at kopiere.
plotDK er pakken!


```
library(httr2)
endpoint <- "http://api.statbank.dk/v1/data"

variables <- list(list(code = "BOPOMR", values = I("*")),
                  list(code = "HFUDD", values = c("H10", "H20", "H30", "H40", "H50", "H60", "H70", "H80", "H90")),
                  list(code = "Tid", values = I(2024))
              )

our_body <- list(table = "HFUDD11", lang = "da", format = "CSV", variables = variables)



resp <- request(endpoint) |>
  req_body_json(our_body) |>
  req_perform()

csv_text <- resp_body_string(resp)


df <- read.csv2(text = csv_text)
df <- df |>mutate(BOPOMR = tolower(BOPOMR))

plotDK::municipality |> head()

library(plotDK)
library(dplyr)
library(ggplot2)
df |> 
  group_by(BOPOMR) |> 
  mutate(totbefolk = sum(INDHOLD)) |> 
  mutate(andel = INDHOLD/totbefolk) |> 
  filter(HFUDD == "H10 Grundskole") |> 
plotDK::plotDK(id = "BOPOMR", value = "andel", interactive = FALSE)  +
  scale_fill_gradient(low = "blue",
                      high = "red")

```